"""Status query and report generation command.
상태 조회 및 리포트 생성 커맨드. TODO.md, TASK_OPERATIONS.md 재생성.
"""
import json
from datetime import datetime
from .utils import get_db, get_project_dir
from ..db.connection import close_connection


def register(subparsers):
    parser = subparsers.add_parser('query', help='Query status and generate reports')
    sub = parser.add_subparsers(dest='subcommand')

    status = sub.add_parser('status', help='Show project status summary')
    status.set_defaults(func=handle_status)

    tasks = sub.add_parser('tasks', help='List tasks by filter')
    tasks.add_argument('--status', help='Filter by status')
    tasks.set_defaults(func=handle_tasks)

    gen_todo = sub.add_parser('generate-todo', help='Regenerate TODO.md from DB')
    gen_todo.set_defaults(func=handle_generate_todo)

    parser.set_defaults(func=lambda args: parser.print_help())


def handle_status(args):
    conn = get_db(args)
    try:
        project = conn.execute(
            "SELECT id, title FROM tasks WHERE type='project' LIMIT 1"
        ).fetchone()
        if not project:
            print("No project found.")
            return

        # Count by type
        epic_count = conn.execute(
            "SELECT COUNT(*) as c FROM tasks WHERE type='epic'"
        ).fetchone()['c']
        task_count = conn.execute(
            "SELECT COUNT(*) as c FROM tasks WHERE type='task'"
        ).fetchone()['c']
        obj_count = conn.execute(
            "SELECT COUNT(*) as c FROM tasks WHERE type='objective'"
        ).fetchone()['c']

        # Count by status (tasks only)
        statuses = conn.execute(
            "SELECT status, COUNT(*) as c FROM tasks WHERE type='task' GROUP BY status"
        ).fetchall()
        status_map = {row['status']: row['c'] for row in statuses}

        done = status_map.get('done', 0)
        total = task_count
        pct = (done / total * 100) if total > 0 else 0

        print(f"Project: {project['title']} ({project['id']})")
        print(f"  Epics: {epic_count}")
        print(f"  Tasks: {task_count}")
        print(f"  Objectives: {obj_count}")
        print(f"  Progress: {done}/{total} ({pct:.0f}%)")
        if status_map:
            print("  Status breakdown:")
            for s in ['todo', 'in_progress', 'interrupted', 'done', 'cancelled']:
                if s in status_map:
                    print(f"    {s}: {status_map[s]}")
    finally:
        close_connection(conn)


def handle_tasks(args):
    conn = get_db(args)
    try:
        query = "SELECT id, title, status, parent_id FROM tasks WHERE type='task'"
        params = []
        if args.status:
            query += " AND status=?"
            params.append(args.status)
        query += " ORDER BY seq_order, id"

        rows = conn.execute(query, params).fetchall()
        if not rows:
            print("No tasks found.")
            return
        for row in rows:
            check = 'x' if row['status'] == 'done' else ' '
            print(f"[{check}] {row['id']}: {row['title']} ({row['status']})")
    finally:
        close_connection(conn)


def handle_generate_todo(args):
    conn = get_db(args)
    try:
        project = conn.execute(
            "SELECT id, title FROM tasks WHERE type='project' LIMIT 1"
        ).fetchone()
        if not project:
            print("No project found.")
            return

        now = datetime.now().isoformat(sep=' ', timespec='seconds')
        lines = []
        lines.append(f"# {project['title']} ({project['id']})")
        lines.append("")
        lines.append(f"> Generated by TaskOps | Last updated: {now}")
        lines.append("")

        # Workflow section
        lines.append("## Workflow")
        lines.append("")
        workflow_tasks = conn.execute(
            "SELECT id, title, parallel_group FROM tasks "
            "WHERE type='task' AND seq_order IS NOT NULL "
            "ORDER BY seq_order, id"
        ).fetchall()

        if workflow_tasks:
            seen_groups = {}
            order_num = 0
            for wt in workflow_tasks:
                group = wt['parallel_group']
                if group and group in seen_groups:
                    lines.append(f"   - {wt['id']}: {wt['title']}")
                elif group:
                    order_num += 1
                    seen_groups[group] = order_num
                    lines.append(f"{order_num}. [parallel-group: {group}]")
                    lines.append(f"   - {wt['id']}: {wt['title']}")
                else:
                    order_num += 1
                    lines.append(f"{order_num}. {wt['id']}: {wt['title']}")
        else:
            lines.append("(No tasks in workflow)")
        lines.append("")

        # ETS section grouped by epic
        epics = conn.execute(
            "SELECT id, title, status FROM tasks WHERE type='epic' ORDER BY id"
        ).fetchall()

        for epic in epics:
            e_status = epic['status'].replace('_', ' ').title()
            lines.append(f"## Epic: {epic['title']} ({epic['id']}) [{e_status}]")
            lines.append("")

            tasks = conn.execute(
                "SELECT id, title, status, description FROM tasks "
                "WHERE type='task' AND parent_id=? ORDER BY seq_order, id",
                (epic['id'],)
            ).fetchall()

            for task in tasks:
                check = 'x' if task['status'] == 'done' else ' '
                lines.append(f"- [{check}] **{task['id']}**: {task['title']} `{task['status']}`")
                if task['description']:
                    lines.append(f"  - {task['description']}")

                # SubTasks
                subtasks = conn.execute(
                    "SELECT id, title, status FROM tasks "
                    "WHERE type='task' AND parent_id=? ORDER BY seq_order, id",
                    (task['id'],)
                ).fetchall()
                for st in subtasks:
                    sc = 'x' if st['status'] == 'done' else ' '
                    lines.append(f"  - [{sc}] {st['id']}: {st['title']} `{st['status']}`")

            lines.append("")

        # Objectives section
        objectives = conn.execute(
            "SELECT id, title, status, milestone_target, due_date "
            "FROM tasks WHERE type='objective' ORDER BY due_date, id"
        ).fetchall()

        lines.append("## Objectives")
        lines.append("")
        if objectives:
            for obj in objectives:
                check = 'x' if obj['status'] == 'done' else ' '
                info = ""
                if obj['milestone_target']:
                    info = f" -- {obj['milestone_target']}"
                if obj['due_date']:
                    info = f" -- {obj['due_date']}"
                lines.append(f"- [{check}] **{obj['title']}**{info}")
        else:
            lines.append("(No objectives)")
        lines.append("")

        # Write file
        project_dir = get_project_dir(args)
        import os
        todo_path = os.path.join(project_dir, 'TODO.md')
        content = '\n'.join(lines)
        with open(todo_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"TODO.md regenerated at {todo_path}")
    finally:
        close_connection(conn)
